### ISSUE TITLE
httpx.ConnectError: EOF occurred in violation of protocol (_ssl.c:997)

### ISSUE THREAD

**Issue by mohsenyzd10** [hldh214/lok_bot#10]
after lunch new version of bot I got this error 
maybe it's related to the not_online issues

 
![image](https://user-images.githubusercontent.com/91246296/154965751-12861b3c-04c9-4020-af13-abcee3a42111.png)
![image](https://user-images.githubusercontent.com/91246296/154965907-db0d14ce-484f-4668-ad45-9a6d02f25fea.png)

**Comment by hldh214** [comment]
Could you try the latest version and see if this still exist?

**Comment by mohsenyzd10** [comment]
the problem solved with new version but when we close the lok page of browser the bot also stop working , it's seems bot disconnect form lok server probably because token expire

**Comment by hldh214** [comment]
Can you put some bot script output here so we can do a further investigation?

**Comment by mohsenyzd10** [comment]
after closing browser bot Get stuck at this line 
![image](https://user-images.githubusercontent.com/91246296/155498378-6ede9e9c-588e-4bff-8154-4753080c9fa3.png)

**Comment by hldh214** [comment]
Please try this commit: 0a40d364ccf7c484f6e00970b29b0c1dc2df1f26

**Comment by mohsenyzd10** [comment]
Bot works after closing browser.
another problem:  castle of my account is level 2, many buildings need to upgrade also many research needed
but I got this 
![image](https://user-images.githubusercontent.com/91246296/155511239-d2f247f9-8458-481f-9fe7-9ea8b0e203b0.png)
![image](https://user-images.githubusercontent.com/91246296/155511718-ccde03c8-77f0-4ef7-bb96-3fbf1875961b.png)

**Comment by mohsenyzd10** [comment]
![image](https://user-images.githubusercontent.com/91246296/155517493-04c83f4c-1cc4-4d81-babe-0705534670ac.png)

**Comment by hldh214** [comment]
Seems this `not_online` issue still exists 😫
I'm gonna close this issue, further discussion related about `not_online` please goto #7
