### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Darklightsite** [hldh214/lok_bot#12]
Hy.
I have this error. Can u help me?

**Comment by hldh214** [comment]
Make sure followed the instruction, see `Prerequisites` and `Install requirements` part.
https://github.com/hldh214/lok_bot#install-requirements

**Comment by Darklightsite** [comment]
I have python and pip and pipenv.
Make pipenv sync and run the bot. 
![IMG_20220225_031215](https://user-images.githubusercontent.com/84232138/155640715-f7fedd8e-91e5-4fbd-a12e-4238f221bcc6.jpg)

**Comment by hldh214** [comment]
Oh dear please hide your token before post it.

**Comment by Darklightsite** [comment]
I Edit

**Comment by hldh214** [comment]
😆 Try `pipenv shell` first, then run your python command.

**Comment by Darklightsite** [comment]
Good, work. Thanks
