### ISSUE TITLE
Not farming

### ISSUE THREAD

**Issue by svenmanderscheid** [hldh214/lok_bot#18]
Is it only for me or does the bot have not farming feature?

Tried to reinstall everything but the bot neither those build troops or sends them to farms.

is there a telegram group i can join to perhaps find even other bots?

**Comment by Kirosai** [comment]
I have the same problem, i can see that i collect every hour the ressources, bought everything in the shop, building (not often) but i'd never seen troops farming on mines

**Comment by zzzhu12** [comment]
Hi , im a newbie in coding is there a help file so i know where to start after downloading the code?
