### ISSUE TITLE
crystal mine

### ISSUE THREAD

**Issue by TomatoBlue** [hldh214/lok_bot#27]
The bot only sends units to mines that are far away. Therefore it is always too late. The ones that appear close do not even try to take.

**Comment by hldh214** [comment]
Consider set lower value for radius
https://github.com/hldh214/lok_bot/blob/ab6f0996dd2e7a14df691cd2bb557f5ccc575ebc/config.example.json#L84

**Comment by TomatoBlue** [comment]
I changed it and now it doesn't send troops at all

**Comment by hldh214** [comment]
The bot will send troops only when mines are found.

**Comment by khunao09** [comment]
how to install?
