### ISSUE TITLE
probability of blocking

### ISSUE THREAD

**Issue by iPowerLife** [hldh214/lok_bot#3]
checked the bot. first I launched 1 account, everything seemed to start working, I went to sleep, I woke up, and the account was blocked (deleted) Then I decided to use 1 more account and watched it in the docker and also got a ban after 1 hour. The question is, what is your bot for then? Or how to avoid blocking?

**Comment by hldh214** [comment]
I'm also very confused about it TBH, as you can see I put a `Disclaimer` at top of readme to emphasize that.
I have registered dozens of accounts, and then basically all of them were banned recently.
Maybe there's some bot-checking mechanism deployed and we just not figured it out.

**Comment by iPowerLife** [comment]
Well, what then to do, dear?) Perhaps you need to set any timings and time for the task? And another question, can you share some kind of bot that is looking for monsters and mines? And it would also be great for a bot for google chrome, which will automatically kill mobs, which I will say.

**Comment by hldh214** [comment]
Currently I'm moving forward analyzing banning strategy on the mobile app, to see if there is any difference between web and mobile.
And talk about browser extension, I'm not very interested in this. Maybe it will happen in the future, or maybe not.

**Comment by MrKurator** [comment]
> Currently I'm moving forward analyzing banning strategy on the mobile app, to see if there is any difference between web and mobile. And talk about browser extension, I'm not very interested in this. Maybe it will happen in the future, or maybe not.

Hi. I failed to install pip install jsonlib, I wrote about it. Trying to write a bot too. On a special program for writing bots. I tested the clicker on mobile, but got banned. + Google captcha appears. I want to know from you what timings and actions are best to do so as not to be banned. I understand that this information should be hidden from the developers, so I invite @valentinkuratov to telegram to discuss these points. I have experience in writing faucet bots, passing captchas. I am sure we will be useful to each other!

**Comment by zzzhu12** [comment]
Hi, I'm complete newbie in github or any programming. How do i start using this?

**Comment by starrock2** [comment]
Same here I just ran this for about 10-15mins.. and after few hours my account was banned.. How can we modify this code to send alerts for crystal mines. Which files I will have to modify. Basically I am looking to modify the code to get only alerts. Code will not do anything in account directly.

**Comment by hldh214** [comment]
Error code list

```json
{"result":false,"err":{"code":"deleted_within_period"}}
```

```json
{"result":false,"err":{"code":"ban_user_2"}}
```
