### ISSUE TITLE
contact you 

### ISSUE THREAD

**Issue by diego0700** [hldh214/lok_bot#44]
I wanted to send you a bot for you to try to have access to the code and implement this one will be very good if you can

**Comment by svenmanderscheid** [comment]
can you send it to me too?

**Comment by admiralsam** [comment]
> I wanted to send you a bot for you to try to have access to the code and implement this one will be very good if you can

Send it to me. i will try to look into it and see if it is possible to Reengineer it

**Comment by diego0700** [comment]
> > I wanted to send you a bot for you to try to have access to the code and implement this one will be very good if you can
> 
> Send it to me. i will try to look into it and see if it is possible to Reengineer it

send me your email bro

**Comment by mohammadgnss** [comment]
> I wanted to send you a bot for you to try to have access to the code and implement this one will be very good if you can

hi bro.. sent to me your bot and i try to crack it
mohammadb160@gmail.com
when you send tell me to check it
