### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by diego0700** [hldh214/lok_bot#45]
![image](https://user-images.githubusercontent.com/104273655/165870454-7774252a-7656-4141-804d-23470795664c.png)

help me fix this please

**Comment by hldh214** [comment]
Please refer to #38

**Comment by diego0700** [comment]
i did still not working 
![image](https://user-images.githubusercontent.com/104273655/166082757-a3c28e70-1c70-422f-80de-b963a46b5a03.png)
