### ISSUE TITLE
Radius

### ISSUE THREAD

**Issue by Eddsss1** [hldh214/lok_bot#49]
Hello,

Even tho i set the radius to 32, the bot sends troops to 1000+ km away. How can I fix that issue?

],
          // radius of the land to search, center: your castle, unit: land
          "radius": 32

**Comment by mohammadgnss** [comment]
set lower like 8

**Comment by hldh214** [comment]
> // radius of the land to search, center: your castle, unit: land

Sorry, I forgot to update readme, the current unit of radius is `zone`, which is bigger than `land`, so you need to set a lower value as @mohammadgnss said.

**Comment by hldh214** [comment]
FYI, one zone contains 4x4 lands, please refer to https://github.com/hldh214/lok_bot/blob/master/docs/land.md for more info.

**Comment by marcussb** [comment]
@mohammadgnss i need to set "set lower like 8" in config.example.json ? or i need set in function socf_thread ?

**Comment by hldh214** [comment]
> @mohammadgnss i need to set "set lower like 8" in config.example.json ? or i need set in function socf_thread ?

Both are workable, set one of them.
