### ISSUE TITLE
I get this error

### ISSUE THREAD

**Issue by Ogr3Knight** [hldh214/lok_bot#52]
PS D:\LoK\lok_bot-master> py -m lokbot eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY3OTZhNWNkMWU4YTExNWY4ZjA2NWQiLCJraW5nZG9tSWQiOiI2MWY3OTZhNWNkMWU4YTExNWY4ZjA2NWUiLCJ2ZXJzaW9uIjoxNDQxLCJ0aW1lIjoxNjUxNzIyNjM4ODA2LCJpYXQiOjE2NTE3MjI2MzgsImV4cCI6MTY1MjMyNzQzOCwiaXNzIjoibm9kZ2FtZXMuY29tIiwic3ViIjoidXNlckluZm8ifQ.McX20q_ZjdMAm3nF7-SDbi-FnWLFBtuHptC1JQkPNzo
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python310\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Program Files\Python310\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\LoK\lok_bot-master\lokbot\__init__.py", line 5, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

**Comment by mohammadgnss** [comment]
enter this codes:
python -m lokbot eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY3OTZhNWNkMWU4YTExNWY4ZjA2NWQiLCJraW5nZG9tSWQiOiI2MWY3OTZhNWNkMWU4YTExNWY4ZjA2NWUiLCJ2ZXJzaW9uIjoxNDQxLCJ0aW1lIjoxNjUxNzIyNjM4ODA2LCJpYXQiOjE2NTE3MjI2MzgsImV4cCI6MTY1MjMyNzQzOCwiaXNzIjoibm9kZ2FtZXMuY29tIiwic3ViIjoidXNlckluZm8ifQ.McX20q_ZjdMAm3nF7-SDbi-FnWLFBtuHptC1JQkPNzo


(change your access code with new one! )

**Comment by Ogr3Knight** [comment]
PS D:\LoK\lok_bot-master> python -m lokbot eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY3OTZhNWNkMWU4YTExNWY4ZjA2NWQiLCJraW5nZG9tSWQiOiI2MWY3OTZhNWNkMWU4YTExNWY4ZjA2NWUiLCJ2ZXJzaW9uIjoxNDQxLCJ0aW1lIjoxNjUxNzIyNjM4ODA2LCJpYXQiOjE2NTE3MjI2MzgsImV4cCI6MTY1MjMyNzQzOCwiaXNzIjoibm9kZ2FtZXMuY29tIiwic3ViIjoidXNlckluZm8ifQ.McX20q_ZjdMAm3nF7-SDbi-FnWLFBtuHptC1JQkPNzo
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python310\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Program Files\Python310\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\LoK\lok_bot-master\lokbot\__init__.py", line 5, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
PS D:\LoK\lok_bot-master>


i still get this error

**Comment by mohammadgnss** [comment]
> PS D:\LoK\lok_bot-master> python -m lokbot eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWY3OTZhNWNkMWU4YTExNWY4ZjA2NWQiLCJraW5nZG9tSWQiOiI2MWY3OTZhNWNkMWU4YTExNWY4ZjA2NWUiLCJ2ZXJzaW9uIjoxNDQxLCJ0aW1lIjoxNjUxNzIyNjM4ODA2LCJpYXQiOjE2NTE3MjI2MzgsImV4cCI6MTY1MjMyNzQzOCwiaXNzIjoibm9kZ2FtZXMuY29tIiwic3ViIjoidXNlckluZm8ifQ.McX20q_ZjdMAm3nF7-SDbi-FnWLFBtuHptC1JQkPNzo Traceback (most recent call last): File "C:\Program Files\Python310\lib\runpy.py", line 187, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "C:\Program Files\Python310\lib\runpy.py", line 146, in _get_module_details return _get_module_details(pkg_main_name, error) File "C:\Program Files\Python310\lib\runpy.py", line 110, in _get_module_details **import**(pkg_name) File "D:\LoK\lok_bot-master\lokbot__init__.py", line 5, in from loguru import logger ModuleNotFoundError: No module named 'loguru' PS D:\LoK\lok_bot-master>
> 
> i still get this error

access code changing every time when you start the game again, try with new access code 
maybe your access code expired.
use NEW access code!

**Comment by hldh214** [comment]
Please install requirements first, ref: https://github.com/hldh214/lok_bot#prerequisites

**Comment by Spong3Bob** [comment]
Was able to get it running now. 

Any guide on how to turn on/off features?
