### ISSUE TITLE
can't farm

### ISSUE THREAD

**Issue by vuminhngoc** [hldh214/lok_bot#54]
when i set this config to farm

`
        "name": "socf_thread",
        "enabled": true,
        "kwargs": {
          "object_code_list": [
            20100105,
	    20100101,
            20200104
          ],
          "radius": 3
        },
        "interval": {
          "start": 1,
          "end": 1
        }
      }
`

this config made a exception

**Comment by mohammadgnss** [comment]
set the upper radius like 8 to find
