### ISSUE TITLE
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/ 

### ISSUE THREAD

**Issue by MrKurator** [hldh214/lok_bot#6]
![Snag_45667fa](https://user-images.githubusercontent.com/86604480/154738983-c5603bc6-8f04-4dd9-8a95-b98b90d5574d.png)
![Snag_10068fd](https://user-images.githubusercontent.com/86604480/154739002-7bae9453-9022-42b0-b160-faa2f512abb6.png)
Installed:
visual studio 2019 build tool
visual studio Community
what to do?

**Comment by hldh214** [comment]
Can you post your full command here?

**Comment by MrKurator** [comment]
pip install jsonlib 
or
pip install jsonlib-python3

**Comment by hldh214** [comment]
May I ask why we need this `jsonlib`?
