### ISSUE TITLE
config.json doesn't work

### ISSUE THREAD

**Issue by Ken24** [hldh214/lok_bot#65]
In the app.py, it seems that `config.json` can be used.

https://github.com/hldh214/lok_bot/blob/b7297b1db25efa9aa29ee2733964f947aab6ac4d/lokbot/app.py#L27-L36

However, in the docker, config.json is not added because the file is ignored by `.dockerignore`
https://github.com/hldh214/lok_bot/blob/b7297b1db25efa9aa29ee2733964f947aab6ac4d/.dockerignore#L1-L8

please add `config.json` lol

**Comment by hldh214** [comment]
The `.dockerignore` file only effect the image building process, accroding to https://docs.docker.com/engine/reference/builder/#dockerignore-file
So if you want to use custom config on `docker run`, try to use docker volume feature
