### ISSUE TITLE
Dear

### ISSUE THREAD

**Issue by iPowerLife** [hldh214/lok_bot#8]
Dear, can you make a separate bot that will periodically kill mobs at a given time, which ones will I indicate? And it would also be great to make a bot that will look for mobs and mines at what levels I indicate.

**Comment by hldh214** [comment]
Attack on monsters via bot will also face issue like #7 in my opinion.
But I think a passive mines/monsters scraper would not.
I'll give a try.

**Comment by iPowerLife** [comment]
просто если ты через телеграм сделаешь, будет замечательно.

**Comment by svenmanderscheid** [comment]
> such a search bot was in the telegram, but disappeared somewhere :D
> 
> [Переслано от Удалённый аккаунт] ▓ Usage: ╚ /charm [-h] [options] ::
> 
> ▓ Requaried arguments: ║ ╠ types ╠ 1 - Harvester ╠ 2 - Lumberjack ╠ 3 - Stonecraft ╠ 4 - Gold mine ╠ 5 - Scholar ╠ 6 - Resources ╠ 7 - Builders ╠ 8 - Trainers ╠ 9 - Stamina ╠ a - Attackers ╠ b - Speed ╠ c - Load ╠ d - Energy ╠ e - Defenders ║ ╠ rare ╠ 1 - Normal ╠ 2 - Magic ╠ 3 - Epic ╚ 4 - Legendary
> 
> ▓ Optional arguments: ║ ╠ -h, --help ╠ information about command ║ ╠ -mc, --march-check ╠ is someone attacking a charm ║ ╠ -r, --radius ╠ charm search radius ╚ default — 250
> 
> ▓ Examples: ║ ╠ /charm -h ╠ /charm 1:1024:1024 12a 1234 -r 120 ╚ /charm 1:1024:1024 6 4 -mc

How can i find such telegram groups? i am looking for one

**Comment by hldh214** [comment]
> > such a search bot was in the telegram, but disappeared somewhere :D
> > [Переслано от Удалённый аккаунт] ▓ Usage: ╚ /charm [-h] [options] ::
> > ▓ Requaried arguments: ║ ╠ types ╠ 1 - Harvester ╠ 2 - Lumberjack ╠ 3 - Stonecraft ╠ 4 - Gold mine ╠ 5 - Scholar ╠ 6 - Resources ╠ 7 - Builders ╠ 8 - Trainers ╠ 9 - Stamina ╠ a - Attackers ╠ b - Speed ╠ c - Load ╠ d - Energy ╠ e - Defenders ║ ╠ rare ╠ 1 - Normal ╠ 2 - Magic ╠ 3 - Epic ╚ 4 - Legendary
> > ▓ Optional arguments: ║ ╠ -h, --help ╠ information about command ║ ╠ -mc, --march-check ╠ is someone attacking a charm ║ ╠ -r, --radius ╠ charm search radius ╚ default — 250
> > ▓ Examples: ║ ╠ /charm -h ╠ /charm 1:1024:1024 12a 1234 -r 120 ╚ /charm 1:1024:1024 6 4 -mc
> 
> How can i find such telegram groups? i am looking for one

https://t.me/LoKSearcherBot
