### ISSUE TITLE
How to get `version` for `auth_set_device_info`

### ISSUE THREAD

**Issue by hldh214** [hldh214/lok_bot#81]
Currently we hard-coded `version` in https://github.com/hldh214/lok_bot/blob/d99030393b6491e84e0e24f5592c2128faadeb7c/lokbot/farmer.py#L96

We needs to find a way to automaticly fetch newest version.

**Comment by svenmanderscheid** [comment]
is there a solution yet for this problem?

**Comment by hldh214** [comment]
not yet
